[package]
name = "libum"
description = "A snake game using wasm"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/d-kja/libum"

[dependencies]
wasm-bindgen = "0.2.92"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]