const RENDER_TIMEOUT = 1000 / 10;

const CELL_SIZE = 25;
const WORLD_SIZE = 25;
const SNAKE_INITIAL_IDX = Date.now() % (WORLD_SIZE * WORLD_SIZE);
const SNAKE_INITIAL_SIZE = 3;

const STROKE_COLOR = '#3f3f46';
const FILL_COLOR = '#3f3f46';
const FILL_HEAD_COLOR = '#52525b';
const FILL_REWARD_COLOR = '#818cf8';

export {
  RENDER_TIMEOUT,
  CELL_SIZE,
  WORLD_SIZE,
  SNAKE_INITIAL_IDX,
  SNAKE_INITIAL_SIZE,
  STROKE_COLOR,
  FILL_COLOR,
  FILL_HEAD_COLOR,
  FILL_REWARD_COLOR
}